name: Tests

on:
  push:
  pull_request:

jobs:
  run_fires_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash tests/func/test_print_fires.sh

  run_utils_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python tests/unit/test_my_utils.py

  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pycodestyle
      - name: Run pycodestyle
        run: |
          git ls-files -z '*.py' | xargs -0 -r pycodestyle